//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tasks
    {
        public System.Guid row_id { get; set; }
        public System.Guid create_by { get; set; }
        public string task_name { get; set; }
        public string task_content { get; set; }
        public System.DateTime create_time { get; set; }
        public bool is_delete { get; set; }
    }
}
